In [2]:
"""
- numpy arrays are similar to C/C++ arrays i.e they are of a fixed data type unlike Python
- less flexible but more efficient for storing & manipulating data unlike Python's dynamic/flexible lists
"""

import numpy as np

##-------------- WAYS TO CREATE NUMPY ARRAYS-----------------
# _____________________________________________________________________________________________
#1. Creating arrays from python lists
np.array([1,4,2,5,3])


array([1, 4, 2, 5, 3])

In [4]:
#if types of elements in the array don't match, Numpy 'upcast's them (int to float in this case:)
np.array([3.142, 4, 2,3])

array([3.142, 4.   , 2.   , 3.   ])

In [6]:
#can also explicitly state data type using dtype keyword:
np.array([1,2,3,4], dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [9]:
#multi-dimensional arrays can also exist in numpy unlike 1D python lists:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# ________________________________________________________________________________________________________________
# 2. Creating arrays from scratch
np.zeros(3, dtype = int)


array([0, 0, 0])

In [6]:
np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.full((3,5), 17, dtype = float)

array([[17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.]])

In [19]:
np.arange(0,10,2)    #similar to range()

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(0,1,5)   #array of 5 values bw 0 & 1 evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.eye(3, dtype = bool)  #3x3 identity matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
#dtype can be bool, int, int8,int16,float etc (table page 42)
# _______________________________________________________________________________________________________________________


In [25]:
#Array attributes: ndim, size, shape, dtype
rng = np.random.default_rng(seed = 42)
x1 = rng.integers(10, size = 6)   #dimension 1, array having integers 0 to 9
x2 = rng.integers (10, size = (3,3))  #2x2 dim
x3 = rng.integers (10, size = (2,3,5)) #3x3 dim

In [30]:
print(f"x1: dim {x1.ndim}, size {x1.size}, shape {x1.shape}, dtype {x1.dtype}")
print(f"x2: dim {x2.ndim}, size {x2.size}, shape {x2.shape}, dtype {x2.dtype}")
print(f"x3: dim {x3.ndim}, size {x3.size}, shape {x3.shape}, dtype {x3.dtype}")

x1: dim 1, size 6, shape (6,), dtype int64
x2: dim 2, size 9, shape (3, 3), dtype int64
x3: dim 3, size 30, shape (2, 3, 5), dtype int64


In [35]:
#Array indexing: similar to python lists. For multi dimensional arrays, use comma bw block/row/cols
x1

array([0, 7, 6, 4, 4, 8])

In [36]:
x1[2]

np.int64(6)

In [37]:
x1[-1]

np.int64(8)

In [38]:
x2

array([[0, 6, 2],
       [0, 5, 9],
       [7, 7, 7]])

In [39]:
x2[0,1]

np.int64(6)

In [40]:
x2[0,0] = 12    #can modify array using index
x2

array([[12,  6,  2],
       [ 0,  5,  9],
       [ 7,  7,  7]])

In [41]:
# _______________________________________________________________________________________________________________________
# Array Slicing (default values [start:end:step] -> [0 : size of dim : 1]
x1      #1D array


array([0, 7, 6, 4, 4, 8])

In [42]:
x1[:]

array([0, 7, 6, 4, 4, 8])

In [43]:
x1[1:3]

array([7, 6])

In [45]:
x1[::2]

array([0, 6, 4])

In [48]:
x1[::-1]    #all elements REVERSED

array([8, 4, 4, 6, 7, 0])

In [44]:
x2     #multi dimensional array

array([[12,  6,  2],
       [ 0,  5,  9],
       [ 7,  7,  7]])

In [47]:
x2[:2,:]

array([[12,  6,  2],
       [ 0,  5,  9]])

In [49]:
x2[:,::2]

array([[12,  2],
       [ 0,  9],
       [ 7,  7]])

In [50]:
"""
- One common use of slicing is that along with indexing, a single row or column can be accessed
- Important to note that these sliced arrays act as VIEWS rather than the copies of array. Modification in sliced arrays results 
in modification in og base array as well.
- .copy() method for creating copies if needed for use
"""
x2[0, :2]   #first row (index = 0) & columns sliced till 2nd column

array([12,  6])

In [51]:
x2

array([[12,  6,  2],
       [ 0,  5,  9],
       [ 7,  7,  7]])

In [52]:
x2_sub = x2[0:2]
x2_sub[0] = 8
x2

array([[8, 8, 8],
       [0, 5, 9],
       [7, 7, 7]])

In [54]:
x2_sub_copy = x2[0:2].copy()
x2_sub_copy[0] = 12     #modification in copy has no effect on the og array
x2

array([[8, 8, 8],
       [0, 5, 9],
       [7, 7, 7]])

In [55]:
#_______________________________________________________________________________________________________________________
# Reshaping Arrays -> reshape() changes the arrangement/shape attribute of data in an array.. ONLY possible if the og size and the reshape size match
np.arange(1,10)    


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(1,10).shape

(9,)

In [57]:
np.arange(1,10).reshape(3,3)      #reshape to 3 rows and 3 cols (3*3 = 9, sizes match so reshape possible)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
#Common use of reshaping: converting 1d array to multi dimensional arrays
x = np.arange(1,4)
x

array([1, 2, 3])

In [61]:
x.shape

(3,)

In [62]:
x.reshape(1,3)

array([[1, 2, 3]])

In [63]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [67]:

#_______________________________________________________________________________________________________________________

# Array concatenation (concatenate(), vstack(), hstack()) & splitting (split(), vsplit(), hsplit())
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
array = np.concatenate([x,y,z])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
grid = np.eye(3, dtype = int)
grid

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [72]:
np.concatenate([grid, grid])     #concatenating 2d arrays

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [73]:
xy_vert = np.vstack([x,y])
xy_vert

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
xy_hor = np.hstack([x,y])
xy_hor

array([1, 2, 3, 4, 5, 6])

In [76]:
#For splitting, we can pass list of indices as splitting point.. NOTE: N splitting points result in N+1 arrays
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x1, x2, x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [78]:
y = np.arange(0,16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
upper, lower = np.vsplit(y, [2])   #vertical split -> split into upper lower 
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [84]:
left, right = np.hsplit(y,[2])     #horizontal split-> split into left right
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
