In [28]:
import numpy as np
"""
Ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
Ufuncs also take additional arguments, like:
    'where' boolean array or condition defining where the operations should take place.
    'dtype' defining the return type of elements.
    'out' output array where the return value should be copied.
Converting iterative statements (loops) into a vector based operation is called vectorization.
"""

#Consider a scenario where we need to calculate the reciprocal of array for which the traditional approach is to loop through the array etc:

rng = np.random.default_rng(seed=1701)

def compute_reciprocal(array):
    output = np.empty(len(array))
    for i in range(len(array)):
        output[i] = 1/array[i]
    return output


array = rng.integers(1,100, size = 1000000)
%timeit compute_reciprocal(array)

466 ms ± 20.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
#now using vectorized operation for the same task:
%timeit 1/array

2.45 ms ± 85.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
#vectorized operations are a wrapper of ufuncs.. like ufunc for / is np.divide(), + is np.add(), np.mod(), np.power() etc.. Examples:

In [ ]:
#SIMPLE OPERATION FUNCTIONS

In [12]:
x = [1,2,3]
np.add(x,2)

array([3, 4, 5])

In [ ]:
#TRIG FUNCTIONS

In [6]:
theta = np.linspace(0,np.pi,3)   #angles array
print("theta: ", theta)

theta:  [0.         1.57079633 3.14159265]


In [9]:
print("sin(theta): ", np.sin(theta))      #similarly cos, tan, arcsin etc

sin(theta):  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
#ABSOLUTE FUNCTIONS

In [10]:
x = [-1 , 0, 1]
np.abs(x)

array([1, 0, 1])

In [11]:
x = 4 - 3j
abs(x)

5.0

In [ ]:
#They can also be used for logs, exponents as well as for other 'special' stuff using gama funcs in scipy

In [ ]:
"""
Advanced Ufunc Features:
- securing the output using out
- aggregation (reduce(), outer()) (group by type shi)
"""

In [18]:
x = np.arange(5)
y = np.empty(5, dtype = int)
print("x = ", x)
np.multiply(x,10, out=y)
print("y = ", y)

x =  [0 1 2 3 4]
y =  [ 0 10 20 30 40]


In [24]:
x = np.arange(5)
y = np.zeros(10, dtype=int)
np.power(2,x,out=y[::2])      #doing y = np.power(...) wouldve resulted in a temporary array which wouldve been copied to y occupying extra time/space 
print(y)

[ 1  0  2  0  4  0  8  0 16  0]


In [26]:
#Aggregation/grouping

In [30]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [33]:
np.add.reduce(x)    #add all numbers in x (hence reducing the array to single digit)

np.int64(15)

In [32]:
np.multiply.reduce(x)

np.int64(120)

In [36]:
np.add.accumulate(x)   # .accumulate() the reduction computation

array([ 1,  3,  6, 10, 15])

In [35]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])